### PR TITLE
fix: handle outdated message in channel queue

### LINKED ISSUE #183: `syncFn` timeout causes subsequent calls to fail.
Whenever there is a long-running function executed in the worker and it's execution time exceeds the timeout configured in `createSyncFn`, the function execution isn't stopped. This means that when it finally finishes and sends the message with response, subsequent calls to the worker will result in this error: `Error: Internal error: Expected id X but got id Y` because always an older message is waiting in the parent message channel queue.

I have prepared this example code:

```javascript
const { runAsWorker, createSyncFn } = require('synckit');
const { isMainThread } = require('worker_threads');

if (isMainThread) {
    const TIMEOUT = 1000;
    const executeSyncTimeout = createSyncFn(__filename, { timeout: TIMEOUT });

    const sleep = (time) => {
        try {
            console.log('sleeping for ' + time);
            executeSyncTimeout(time);
        } catch (e) {
            console.log(e);
        }
    };

    sleep(TIMEOUT / 2); // id = 0; success because shorter than timeout
    sleep(TIMEOUT * 2); // id = 1; task is longer than timeout -> error in parent thread, but task continues in worker
    sleep(TIMEOUT / 2); // id = 2; success because shorter than timeout and long task in worker hasn't finished yet
    sleep(TIMEOUT / 2); // id = 3; error because long task in worker (id 1) finished and sent it's message to parent
    sleep(TIMEOUT / 2); // id = 4; error because message from task id 3 is still in message queue
    sleep(TIMEOUT / 2); // id = 5; error because message from task id 4 is still in message queue
} else {
    runAsWorker(async (sleepTime) => {
        await new Promise((resolve) => {
            setTimeout(resolve, sleepTime);
        });
    });
}

```

which results in these logs being printed:
```
sleeping for 500
sleeping for 2000
Error: Internal error: Atomics.wait() failed: timed-out
sleeping for 500
sleeping for 500
Error: Internal error: Expected id 3 but got id 1
sleeping for 500
Error: Internal error: Expected id 4 but got id 3
sleeping for 500
Error: Internal error: Expected id 5 but got id 4
```

### PR DESCRIPTION
**Pull request by jedlikowski**
Fixes #183

### CODE REVIEW

**Comment by JounQin** [comment]
What's the issue here? Can you provide more information? Reproduction or failing test for example.

**Comment by jedlikowski** [comment]
Hi, sorry, it was meant to be a draft PR ;) I've added in the description an issue which this PR means to fix.

**Comment by jedlikowski** [comment]
Hi, I've added one more change to avoid sending the worker task result to parent if parent isn't waiting for the result anymore. Let me know what you think of this PR and I'll be happy to carry it to the end :)

**Comment by jedlikowski** [comment]
Hi, @JounQin, what do you think of this PR? Would you be interested in such a contribution?

**Comment by KubaZ** [comment]
Hi @JounQin, could you please take a look at this PR?

**Comment by JounQin** [comment]
Interesting, is that possible to add a related test case?

**Comment by jedlikowski** [comment]
> Interesting, is that possible to add a related test case?

Hi @JounQin , I've added a test case that will currently fail on `main` branch and pass on this branch: https://github.com/un-ts/synckit/pull/184/files#diff-708937a178903f6cba26c362f7fda7d1da8fb676b66c79dbd63fbffdc7a2db96R107-R125

image

**Comment by JounQin** [comment]
Could all lines except `if (expectedId !== id)` be test covered?

**Comment by jedlikowski** [comment]
> Could all lines except `if (expectedId !== id)` be test covered?

I've been trying to achieve that. AFAIK these are the only other lines not covered:
```typescript
if (id < expectedId) {
  const waitingTime = Date.now() - start
  return receiveMessageWithId(
    port,
    expectedId,
    waitingTimeout ? waitingTimeout - waitingTime : undefined,
  )
}
```

Adding coverage for them in a stable manner would require us to mock `receiveMessageOnPort` so that it returns `expectedId - 1` on first call and `expectedId` on second call. This is currently not possible in `jest` in ESM environment, because partial module mocking [is not supported](https://github.com/jestjs/jest/issues/15100#issuecomment-2142720180). Due to lack of support, it would be required to mock the whole `node:worker_threads` module 😞

**Comment by jedlikowski** [comment]
Good news @JounQin, I've managed to bring coverage back to 100% 😄  Could you take a look?

**Comment by JounQin** [comment]
Thanks for your contribution!

**Pull request merged**
